module.exports = {
  apps: [
    {
      name: 'kale-farmer',
      script: 'bun',
      args: 'run plant_and_work.ts',
      cwd: '../',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/kale-farmer-error.log',
      out_file: './logs/kale-farmer-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
      exp_backoff_restart_delay: 100,
      kill_timeout: 3000,
    },
    {
      name: 'kale-farmer-testnet',
      script: 'bun',
      args: 'run --env-file=.env.testnet plant_and_work.ts',
      cwd: '../',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/kale-farmer-testnet-error.log',
      out_file: './logs/kale-farmer-testnet-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
      exp_backoff_restart_delay: 100,
      kill_timeout: 3000,
    },
    {
      name: 'kale-farmer-futurenet',
      script: 'bun',
      args: 'run --env-file=.env.futurenet plant_and_work.ts',
      cwd: '../',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/kale-farmer-futurenet-error.log',
      out_file: './logs/kale-farmer-futurenet-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
      exp_backoff_restart_delay: 100,
      kill_timeout: 3000,
    },
  ],
};
